# Generated by Django 5.0.3 on 2025-04-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nastavitev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(choices=[('tema', 'Tema'), ('jezik', 'Jezik'), ('notifikacije', 'Notifikacije'), ('avtomatska_odjava', 'Avtomatska odjava')], max_length=50)),
                ('vrednost', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100)),
                ('nastavitve', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('osebna_stevilka', models.CharField(max_length=50)),
                ('datum', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('nastavitve_segmentov', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'tipi',
            },
        ),
        migrations.CreateModel(
            name='LogSprememb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cas', models.DateTimeField(auto_now_add=True)),
                ('sprememba', models.CharField(max_length=200)),
                ('stara_vrednost', models.TextField(blank=True, null=True)),
                ('nova_vrednost', models.TextField(blank=True, null=True)),
                ('uporabnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjektTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilo_ponovitev', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projekt_tipi', to='checklist.projekt')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklist.tip')),
            ],
            options={
                'unique_together': {('projekt', 'tip')},
            },
        ),
        migrations.CreateModel(
            name='SerijskaStevilka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stevilka', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serijske_stevilke', to='checklist.projekt')),
                ('projekt_tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serijske_stevilke', to='checklist.projekttip')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_segmenti', to='checklist.tip')),
            ],
        ),
        migrations.CreateModel(
            name='Vprasanje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vprasanje', models.TextField()),
                ('tip', models.CharField(choices=[('boolean', 'Da/Ne'), ('multiple_choice', 'Več izbir'), ('textual', 'Besedilo')], max_length=20)),
                ('repeatability', models.BooleanField(default=False)),
                ('obvezno', models.BooleanField(default=True)),
                ('opis', models.TextField(blank=True)),
                ('moznosti', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vprasanja', to='checklist.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Odgovor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('odgovor', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serijska_stevilka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odgovori', to='checklist.serijskastevilka')),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odgovori', to='checklist.vprasanje')),
            ],
        ),
    ]
